dist: trusty
language: java
jdk:
  - openjdk17


before_install:
  - chmod +x mvnw  # Make the Maven wrapper executable

script:
  - ./mvnw clean test -Dbrowser=chrome
  - ./mvnw allure:report


after_success:
  - zip -r target.zip target
  - export ZIP_URL=$(curl -k --upload-file ./target.zip https://transfer.sh/target.zip)
  - echo "<<< Download the zip file here ${ZIP_URL} >>>"


notifications:
  email:
    on_success: always # default: change
    on_failure: always # default: always