sudo: required
dist: trusty
language: java
jdk:
  - openjdk17

#addons:
#  chrome: stable   # Make sure to specify Chrome
#  firefox: latest  # Specify Firefox if needed

before_install:
  - chmod +x mvnw  # Make the Maven wrapper executable

script:
  - ./mvnw clean test -Dbrowser=chrome
  - ./mvnw allure:report

after_success:
  - zip -r target.zip target

#notifications:
#  email:
#    on_success: change # default: change
#    on_failure: always # default: always