sudo: required
dist: trusty
language: java
jdk:
  - openjdk17

#addons:
#  chrome: stable   # Make sure to specify Chrome
#  firefox: latest  # Specify Firefox if needed

before_install:
  - chmod +x mvnw  # Make the Maven wrapper executable

script:
  - ./mvnw clean test -Dbrowser=chrome
  #- ./mvnw allure:report
  - ./mvnw allure:serve


addons:
  chrome: stable


notifications:
  email:
#    recipients:
#      - one@example.com
#      - other@example.com
    on_success: change # default: change
    on_failure: always # default: always

after_success:
  - sleep 15  # Adjust the duration based on your needs (how long to wait for the server to start)
  - pkill -f "allure serve"